### 
# @prompt username
# @prompt password
# @name login
POST http://localhost:8000/token/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}


####
# @name call_api
GET http://localhost:8000
Content-Type: application/json
Authorization: Bearer {{login.response.body.access}}

